org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
org.gradle.configuration-cache=false

minecraft_version=1.21.8
yarn_mappings=1.21.8+build.1
loader_version=0.16.14
loom_version=1.11.8
fabric_api_version=0.129.0+1.21.8
baritone_version=1.15.0
baritone_jar=../dependencies/baritone-api-fabric-1.15.0.jar

maven_group=dev.entity
archives_base_name=entity2-client
